language: rust
rust:
  - stable
  - beta
  - nightly
addons:
  # Force the latest firefox, otherwise we get an old ESR version
  # that we don't even support
  firefox: latest
  chrome: stable
  apt:
    packages:
    - xvfb
before_script:
  - source bin/travis/before
script:
  - TC="${TRAVIS_RUST_VERSION}" bin/build_tc
